dealer/config/routes.rb
Rails.application.routes.draw do
  use_twirp

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root 'home#index'

  resources :home, only: %i[index]

  resources :remotes, only: %i[index], param: :name do
    resources :files, only: %i[index], controller: 'remotes/files'
  end
  resources :file_selections, only: %i[create show destroy] do
    resources :items, only: %i[], controller: 'file_selections/items' do
      member do
        post :hide
        post :reveal
      end
    end
  end
  resources :media_meta_reports, only: %i[show create]
  resources :orders, only: %i[index new create edit update show] do
    collection do
      get :choose_type
    end

    member do
      post :cancel
    end
  end
end

dealer/app/models/file_selection.rb
# == Schema Information
#
# Table name: file_selections
#
#  id                :uuid             not null, primary key
#  items_count       :integer
#  reached_max_depth :boolean          default(FALSE), not null
#  root_rclone_path  :string
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#
class FileSelection < ApplicationRecord
  has_many :items, dependent: :destroy, class_name: 'FileSelectionItem'
  has_many :orders, dependent: :restrict_with_error

  def video_items?
    items.reject(&:removed).any?(&:video?)
  end

  def audio_items?
    items.reject(&:removed).any?(&:audio?)
  end
end

dealer/app/controllers/file_selections/items_controller.rb
class FileSelections::ItemsController < ApplicationController
  before_action :set_file_selection
  before_action :set_file_selection_item

  def reveal
    @file_selection_item.update!(removed: false)
    redirect_to @file_selection
  end

  def hide
    @file_selection_item.update!(removed: true)
    redirect_to @file_selection
  end

  private def set_file_selection
    @file_selection = FileSelection.find(params[:file_selection_id])
  end

  private def set_file_selection_item
    @file_selection_item = @file_selection.items.unscoped.find(params[:id])
  end
end

dealer/app/controllers/file_selections_controller.rb
class FileSelectionsController < ApplicationController
  before_action :set_file_selection, only: %i[show destroy]
  before_action :set_file_selection_item, only: %i[hide_item show_item]

  helper_method :media_meta_for_item

  def create
    service = SearchFilesService.new(
      rclone_path: params[:path],
      mime_type: /^(video|audio)\/.+/,
      file_name: /(^[^.]).+/
    )

    unless service.perform
      redirect_back alert: "Failed to search files: #{service.errors.full_messages.join(', ')}"
      return
    end

    @file_selection = service.file_selection
    session[:current_file_selection_id] = @file_selection.id

    redirect_to file_selection_path(id: @file_selection.id)
  end

  def show
    @items =
      FileSelectionItem
        .unscoped
        .where(file_selection: @file_selection)
        .order(rclone_path: :asc)

    meta_tuples = @items.map do |item|
      [item.rclone_path, item.size]
    end

    @media_meta_reports =
      MediaMetaReport
        .by_path_and_size(meta_tuples)
        .order(created_at: :asc)
        .index_by { |media_meta_report| [media_meta_report.rclone_path, media_meta_report.size] }
  end

  def hide_item
  end

  def show_item
  end

  def destroy
    @file_selection.destroy
    redirect_to remote_files_path(remote_name: @remote_name, path: @remote_path)
  end

  private def set_file_selection
    @file_selection = FileSelection.find(params[:id])

    parsed_path = Rclone.parse(@file_selection.root_rclone_path)
    @remote_name = parsed_path[:remote]
    @remote_path = parsed_path[:path]
  end

  private def media_meta_for_item(item)
    @media_meta_reports[[item.rclone_path, item.size]]
  end
end

dealer/app/views/file_selections/show.html.slim
- content_for :header do
  .d-inline.ms-3
    = button_to media_meta_reports_path(file_selection_id: @file_selection.id), class: 'btn btn-secondary', form: { class: 'd-inline' }
      | Collect metadata
  .d-inline.ms-3
    = button_to choose_type_orders_path, method: :get, class: 'btn btn-warning', form: { class: 'd-inline' }
      | Create order

div
  = render 'shared/remote_path', path: @file_selection.root_rclone_path

table.table.table-striped
  thead
    tr
      th(style="width: 2rem;") = check_box_tag(name: :all)
      th(style="width: 2rem;")
      th Name
      th Size
      th Meta
      th
  tbody
    - @items.each do |item|
      tr(style="line-height: 1.9rem;", class="#{'text-secondary' if item.removed?}")
        td
          - if item.removed?
            = button_to reveal_file_selection_item_path(file_selection_id: @file_selection.id, id: item.id), method: :post, class: 'btn btn-sm btn-success fs-6', form: { class: 'd-inline' }
              i.bi.bi-arrow-counterclockwise
          - else
            = button_to hide_file_selection_item_path(file_selection_id: @file_selection.id, id: item.id), method: :post, class: 'btn btn-sm btn-light fs-6', form: { class: 'd-inline' }
              i.bi.bi-x

        td(style="width: 2rem;")
          i(class=mime_type_icon(item[:mime_type]))
        td = item.rclone_path
        td
          - unless item.size.negative?
            = number_to_human_size(item.size)
        td
          - if media_meta_for_item(item)
            = link_to media_meta_for_item(item)
              i.bi.bi-check-lg
        td