dealer/config/routes.rb
Rails.application.routes.draw do
  use_twirp

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root 'home#index'

  resources :home, only: %i[index]

  resources :remotes, only: %i[index], param: :name do
    resources :files, only: %i[index], controller: 'remotes/files'
  end
  resources :file_selections, only: %i[create show destroy] do
    resources :items, only: %i[], controller: 'file_selections/items' do
      member do
        post :hide
        post :reveal
      end
    end
  end
  resources :media_meta_reports, only: %i[show create]
  resources :orders, only: %i[index new create edit update show] do
    collection do
      get :choose_type
    end

    member do
      post :cancel
    end
  end
end

dealer/app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id                :uuid             not null, primary key
#  payload_type      :string           not null
#  state             :string           default("created")
#  type              :string
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  file_selection_id :uuid
#  payload_id        :uuid             not null
#
# Indexes
#
#  index_orders_on_file_selection_id  (file_selection_id)
#
# Foreign Keys
#
#  fk_rails_...  (file_selection_id => file_selections.id)
#
class Order < ApplicationRecord
  extend Enumerize

  belongs_to :payload, polymorphic: true, dependent: :destroy
  belongs_to :file_selection, optional: true

  has_many :tasks, inverse_of: :order, dependent: :destroy

  enumerize :state, in: %i[created published cancelled], scope: true

  accepts_nested_attributes_for :payload,
                                :tasks

  def short_type
    ActiveSupport::StringInquirer.new(type.split('::').last.underscore)
  end

  def set_default_values
  end

  def build_payload(*args)
    raise NotImplementedError
  end

  def publish
    self.state = :published
    tasks.each { |t| t.state = :published }
  end

  def cancel
    self.state = :cancelled
    tasks.each { |t| t.state = :cancelled }
  end
end

dealer/app/models/orders/convert.rb
# == Schema Information
#
# Table name: orders
#
#  id                :uuid             not null, primary key
#  payload_type      :string           not null
#  state             :string           default("created")
#  type              :string
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  file_selection_id :uuid
#  payload_id        :uuid             not null
#
# Indexes
#
#  index_orders_on_file_selection_id  (file_selection_id)
#
# Foreign Keys
#
#  fk_rails_...  (file_selection_id => file_selections.id)
#
class Orders::Convert < Order
  validate :ensure_payload_has_correct_type

  def set_default_values
    super()

    unless payload
      self.payload = Payloads::Orders::Convert.new
      payload.set_default_values
    end
  end

  def build_payload(params = {})
    self.payload = Payloads::Orders::Convert.new(params.except(:type))
  end

  private def ensure_payload_has_correct_type
    errors.add(:base, "Incorrect payload type: `#{payload.class.name}`") if payload.class != Payloads::Orders::Convert
  end
end

dealer/app/models/payloads/orders/convert.rb
# == Schema Information
#
# Table name: convert_order_payloads
#
#  id                 :uuid             not null, primary key
#  audio_muxer        :string
#  audio_opts         :string
#  output_rclone_path :string
#  video_muxer        :string
#  video_opts         :string
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#
class Payloads::Orders::Convert < ApplicationRecord
  self.table_name = :convert_order_payloads

  validates :output_rclone_path, presence: true

  def set_default_values
    defaults = config.dig(:order_defaults, :convert)

    self.id ||= SecureRandom.uuid
    self.video_muxer ||= defaults[:video_muxer]
    self.video_opts ||= defaults[:video_opts]
    self.audio_muxer ||= defaults[:audio_muxer]
    self.audio_opts ||= defaults[:audio_opts]

    self.output_rclone_path ||= Rclone.join_path(
      defaults[:output_location],
      Time.zone.today.to_s,
      id,
      '/'
    )
  end
end

dealer/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  PUBLISH_COMMIT = 'Publish'.freeze
  REBUILD_COMMIT = 'Rebuild tasks'.freeze
  ALLOWED_ORDER_TYPES = [
    Orders::Convert
  ].map(&:name).freeze

  before_action :set_order, except: %i[index choose_type new create]

  def index
    @orders = Order.page(params[:page]).per(30)
  end

  def choose_type
  end

  def new
    @order = Order.new(permitted_params)

    if @order.type.blank?
      return redirect_to choose_type_orders_path
    end

    @order.file_selection = current_file_selection
    @order.set_default_values
  end

  def create
    @order = order_class.new(permitted_params)
    @order.file_selection = current_file_selection

    result = apply_changes(build_tasks: true) do
      @order.set_default_values
    end

    if result
      redirect_to edit_order_path(@order)
    else
      render :new
    end
  end

  def show
  end

  def edit
    if @order.state.published?
      redirect_to order_path(@order)
      return
    end

    render :edit
  end

  def update
    result = apply_changes(build_tasks: params[:commit] == REBUILD_COMMIT) do
      @order.publish if params[:commit] == PUBLISH_COMMIT
    end

    if result
      redirect_to edit_order_path(@order)
    else
      render :edit
    end
  end

  def cancel
    @order.cancel

    unless @order.save
      flash[:alert] = "Failed to cancel order: #{human_errors(@order.errors)}"
    end

    redirect_to action: :show
  end

  private def set_order
    @order = Order.find(params[:id])
  end

  # rubocop:disable Style/SymbolArray
  private def permitted_params
    f_params = params.fetch(:order, {}).permit(:type)
    is_convert_order = params.fetch(:orders_convert, {}).permit!.present?

    if is_convert_order
      params
        .require(:orders_convert)
        .permit(
          payload_attributes: [
            :id,
            :video_muxer,
            :video_opts,
            :audio_muxer,
            :audio_opts,
            :output_rclone_path
          ],
          tasks_attributes: [
            :id,
            :_destroy,
            payload_attributes: [
              :id,
              :input_rclone_path,
              :output_rclone_path,
              :string_opts
            ]
          ]
        ).tap do |p_params|
          p_params[:type] = Orders::Convert.name
          p_params[:file_selection_id] = current_file_selection&.id
        end
    else
      f_params
    end
  end
  # rubocop:enable Style/SymbolArray

  private def order_class
    (([permitted_params[:type]] & ALLOWED_ORDER_TYPES).first || 'Order').constantize
  end

  private def apply_changes(build_tasks: false)
    result = true

    Order.transaction do
      @order.assign_attributes(permitted_params)

      yield if block_given?

      unless @order.save
        raise ActiveRecord::Rollback
      end

      if build_tasks
        build_service = BuildConvertOrderService.new(@order)

        unless build_service.perform
          @order.errors.add(:base, "Failed to build tasks: #{build_service.errors.full_messages.join(', ')}")
          raise ActiveRecord::Rollback
        end
      end
    rescue ActiveRecord::Rollback => e
      result = false
      raise e
    end

    result
  end
end

dealer/app/views/orders/_form.html.slim
ruby:
  if @order.type.blank?
    url = new_order_path
    method = :get
  elsif !@order.persisted?
    url = orders_path
    method = :post
  else
    url = order_path(@order)
    method = :patch
  end

= simple_form_for @order, url: url, method: method, data: { turbo: false } do |f|
  = f.error_notification message: f.object.errors.full_messages.join('; ')

  = f.input :type, as: :select, collection: [Orders::Convert].map(&:name), disabled: f.object.type.present?

  - if f.object.type.present?
    = render "orders/typed_forms/#{f.object.type.split('::').last.underscore}", f: f

  - if f.object.persisted?
    = f.submit OrdersController::REBUILD_COMMIT, class: 'btn btn-warning ms-2'

  - if f.object.tasks.present?
    = f.simple_fields_for :tasks do |tf|
      .bs-emphasis.py-3.mt-5.rounded
        = render "tasks/typed_forms/#{f.object.type.split('::').last.underscore}", f: tf

  = f.submit f.object.persisted? ? 'Save' : 'Next', class: 'btn btn-primary'

  - if f.object.tasks.present?
    = f.submit OrdersController::PUBLISH_COMMIT, class: 'btn btn-warning ms-2'
    = f.submit OrdersController::REBUILD_COMMIT, class: 'btn btn-warning ms-2'

dealer/app/views/orders/choose_type.html.slim
= link_to "Convert", new_order_path(order: { type: 'Orders::Convert' })

dealer/app/views/orders/edit.html.slim
.mb-5
  = render 'form'

dealer/app/views/orders/index.html.slim
table.table.mt-5
  thead
    tr
      th ID
      th State
      th Created at
      th
  tbody
    - @orders.each do |order|
      tr
        td
          samp = order.id
        td = order.state
        td = l(order.created_at, format: :mod_time)
        td
          = link_to order_path(order.id), class: 'btn btn-light float-end'
            i.bi.bi-eye-fill

.mt-5.center
  = paginate @orders, theme: 'bootstrap-5'

dealer/app/views/orders/new.html.slim
= render 'form'

dealer/app/views/orders/show.html.slim
- content_for :header do
  - unless @order.state.cancelled?
    .d-inline.ms-3
      = button_to cancel_order_path(@order), class: 'btn btn-danger', form: { class: 'd-inline' }
        | Cancel

nav.my-3.breadcrumb
  ol.breadcrumb
    li.breadcrumb-item
      = link_to "Home", root_path
    li.breadcrumb-item
      = link_to "Orders", orders_path
    li.breadcrumb-item
      samp
        = link_to @order.id, order_path(@order)

h2
  | Order

table.table
  tbody
    tr
      th ID
      td
        code = @order.id
    tr
      th State
      td
        code = @order.state
    - if @order.short_type.convert?
      - if @order.payload.video_opts.present?
        tr
          th Video opts
          td
            code == @order.payload.video_opts.gsub("\n", '<br/>')
      - if @order.payload.audio_opts.present?
        tr
          th Audio opts
          td
            code == @order.payload.audio_opts.gsub("\n", '<br/>')
      - if @order.file_selection_id.present?
        tr
          th File selection
          td
            = link_to 'Open', file_selection_path(@order.file_selection_id)
      - if @order.payload.output_rclone_path.present?
        tr
          th Output
          td
            = link_to_path @order.payload.output_rclone_path
              code = @order.payload.output_rclone_path

h2.mt-5 Tasks

table.table
  thead
    tr
      th ID
      th State
      th Type
      th Step
      th Progress
  tbody
    - @order.tasks.decorate.each do |task|
      tr.bg-light.fw-bold
        td(style="width: 23rem;")
          code = task.id
        td = task.state
        td = task.short_type
        td = task.human_step
        td = task.human_progress
      - if task.short_type.convert?
        tr
          td.ps-5 input
          td(colspan=4)
            = link_to_path task.payload.input_rclone_path
              code = task.payload.input_rclone_path
        tr
          td.ps-5 output
          td(colspan=4)
            = link_to_path task.payload.output_rclone_path
              code = task.payload.output_rclone_path