dealer/config/routes.rb
Rails.application.routes.draw do
  use_twirp

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root 'home#index'

  resources :home, only: %i[index]

  resources :remotes, only: %i[index], param: :name do
    resources :files, only: %i[index], controller: 'remotes/files'
  end
  resources :file_selections, only: %i[create show destroy] do
    resources :items, only: %i[], controller: 'file_selections/items' do
      member do
        post :hide
        post :reveal
      end
    end
  end
  resources :media_meta_reports, only: %i[show create]
  resources :orders, only: %i[index new create edit update show] do
    collection do
      get :choose_type
    end

    member do
      post :cancel
    end
  end
end

dealer/app/controllers/remotes/files_controller.rb
module Remotes
  class FilesController < ApplicationController
    helper_method :media_meta_report_for_entry

    def index
      @remote = params[:remote_name]

      unless @remote
        redirect_to remotes_path, alert: 'Missing remote name'
        return
      end

      @entries =
        Rclone.ls("#{params[:remote_name]}:#{File.join('/', params[:path])}")
              .reject { |entry| ignore_entry?(entry) }
              .sort_by { |entry| [entry[:is_dir] ? 0 : 1, entry[:name]] }

      meta_tuples = @entries.map do |entry|
        [entry[:full_path], entry[:size]]
      end

      @media_meta_reports =
        MediaMetaReport.by_path_and_size(meta_tuples)
                       .order(created_at: :asc)
                       .index_by { |media_meta_report| [media_meta_report.rclone_path, media_meta_report.size] }
    end

    private def ignore_entry?(entry)
      entry[:name].match?(/DS_Store/) || \
      (entry[:name].start_with?('.') && entry[:size] == 4.kilobytes)
    end

    private def media_meta_report_for_entry(entry)
      @media_meta_reports[[entry[:full_path], entry[:size]]]
    end
  end
end

dealer/app/controllers/remotes_controller.rb
class RemotesController < ApplicationController
  def index
    @remotes = Rclone.remotes
  end
end

dealer/app/views/remotes/files/index.html.slim
- if params[:path].presence
  = render 'shared/remote_path', path: "#{@remote}:#{params[:path]}"

table.table
  thead
    tr
      th(style="width: 2rem;") = check_box_tag(name: :all)
      th(style="width: 2rem;")
      th Name
      th Size
      th Modified at
      th
  tbody
    - @entries.each do |entry|
      tr(style="line-height: 2.1rem;")
        td = check_box_tag(name: "paths[#{entry[:full_path]}]")
        td(style="width: 2rem;")
          i(class=mime_type_icon(entry[:mime_type]))
        td
          - if entry[:is_dir]
            = link_to remote_files_path(remote_name: @remote, path: File.join(*[params[:path], entry[:path]].compact)) do
              = entry[:name]
          - else
            = entry[:name]
        td
          - unless entry[:size].negative?
            = number_to_human_size(entry[:size])
        td = l(entry[:mod_time], format: :mod_time)
        td
          .btn-group.actions_btns
            - if media_meta_report_for_entry(entry)
              = link_to media_meta_report_for_entry(entry), class: 'btn btn-light'
                  i.bi.bi-clipboard-data-fill
            - elsif media_mime_type?(entry[:mime_type])
              = button_to media_meta_reports_path(path: entry[:full_path]), class: 'btn btn-light'
                i.bi.bi-eyeglasses

            - if entry[:is_dir]
              = button_to file_selections_path(path: entry[:full_path]), class: 'btn btn-light'
                i.bi.bi-search