dealer/config/routes.rb
Rails.application.routes.draw do
  use_twirp

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root 'home#index'

  resources :home, only: %i[index]

  resources :remotes, only: %i[index], param: :name do
    resources :files, only: %i[index], controller: 'remotes/files'
  end
  resources :file_selections, only: %i[create show destroy] do
    resources :items, only: %i[], controller: 'file_selections/items' do
      member do
        post :hide
        post :reveal
      end
    end
  end
  resources :media_meta_reports, only: %i[show create]
  resources :orders, only: %i[index new create edit update show] do
    collection do
      get :choose_type
    end

    member do
      post :cancel
    end
  end
end

dealer/app/views/shared/_header.html.slim
ruby:
  active_selection ||= defined?(@file_selection) && @file_selection == current_file_selection

div.my-3
  = link_to remotes_path do
      button.btn.btn-info
        i.bi.bi-house-door

  - if current_file_selection
    .btn-group.ms-3
      = button_to file_selection_path(id: current_file_selection.id), method: :get, class: "btn btn-#{active_selection ? 'primary' : 'secondary'} btn_group_beginning" do
        = format(\
            'File selection: %{not_removed_count} (%{total_count})',\
            not_removed_count: current_file_selection.items.unscoped.not_removed.count,\
            total_count: current_file_selection.items_count)
      = button_to file_selection_path(id: current_file_selection.id), method: :delete, class: "btn btn-#{active_selection ? 'primary' : 'secondary'} btn_group_end" do
        i.bi.bi-x-lg

  = yield :header

dealer/app/views/shared/_remote_path.html.slim
ruby:
  parsed = Rclone.parse(path)
  remote_name = parsed[:remote] || ''
  remote_path = parsed[:path]

nav.my-3.breadcrumb
  ol.breadcrumb
    li.breadcrumb-item.active.fw-bold
      = link_to remote_files_path(remote_name: remote_name, path: '/') do
        = remote_name

    - Pathname.new(remote_path).each_filename.to_a.inject("") do |prev, entry|
      - prev = "#{prev}#{entry}/"
      li.breadcrumb-item.active
        = link_to remote_files_path(remote_name: remote_name, path: prev) do
          = entry
      - next prev